@startuml TF2_Testbed

skinparam monochrome true

hide footbox

actor User
participant FrontEnd
participant BackEnd
participant TestRunner
database DB
database NoSQLDB

group ログイン

    User -> FrontEnd : ログイン情報入力
    activate FrontEnd

    FrontEnd -> BackEnd : POST /login
    activate BackEnd
    note left
      <Request>
      {
          UserName:"akita",
          Password:"{ハッシュ化済みパスワード}"
      }
    end note

    BackEnd -> DB : ユーザ認証
    activate DB
    BackEnd <- DB : ユーザ認証結果
    deactivate DB

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          Organizer{
              Id:"Xcorp-Dev",
              Name:"X社　開発部"
          }
      }
    end note
    deactivate BackEnd

    group プロジェクト一覧表示
        FrontEnd -> FrontEnd : プロジェクト一覧画面へ遷移
        activate FrontEnd
            FrontEnd -> BackEnd : GET /Xcorp-Dev/projects
            activate BackEnd
            note left
            <Request>
            None
            end note

            BackEnd -> DB : プロジェクト一覧取得
            activate DB
            BackEnd <- DB : プロジェクト一覧
            deactivate DB

            FrontEnd <- BackEnd : response
            note right
            <Response>
            {
                Result:{
                    Code:0,
                    Message:"Success"
                },
                Projects:
                [
                    {
                        Id:1,
                        Name:"A社住宅価格予測システム"
                    },
                    {
                        Id:2,
                        Name:"B社文字認識システム"
                    },
                    {
                        Id:3,
                        Name:"C社ゴルフスコア読み取りシステム"
                    }
                ]
            }
            end note
            deactivate BackEnd
        User <- FrontEnd : プロジェクト一覧画面
        deactivate FrontEnd
    end

    deactivate FrontEnd
end

group project追加
end

group project編集
end

group project複製
end

group project削除
end

group asset一覧表示

    User -> FrontEnd : project1「A社住宅価格予測システム」を選択
    activate FrontEnd

    FrontEnd -> BackEnd : GET /Xcorp-Dev/projects/1/assets
    activate BackEnd
    note left
      <Request>
      None
    end note

    BackEnd -> DB : アセット一覧取得
    activate DB
    BackEnd <- DB : アセット一覧
    deactivate DB

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          Assets:
          [
              {
                Id:1,
                Name:"House price train data",
                Description:"...",
                AssetFileName:"train.csv",
                AssetDownloadLink:"https://hogehoge1"
              },
              {
                Id:2,
                Name:"House price test data",
                Description:"...",
                AssetFileName:"test.csv",
                AssetDownloadLink:"https://hogehoge2"
              },
              {
                Id:3,
                Name:"House price attribute",
                Description:"...",
                AssetFileName:"attribute.json",
                AssetDownloadLink:"https://hogehoge3"
              },
              {
                Id:4,
                Name:"TestDataset_1018",
                Description:"...",
                AssetFileName:"test_1018.csv",
                AssetDownloadLink:"https://hogehoge4"
              },
              {
                Id:5,
                Name:"TrainedModel_1007",
                Description:"...",
                AssetFileName:"model_1007.h5",
                AssetDownloadLink:"https://hogehoge5"
              }
          ]
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : assets画面
    deactivate FrontEnd
end

group asset追加
end

group asset編集
end

group asset削除
end

group assetダウンロード
end

/' 10/25 FB ここから
group test一覧表示
    User -> FrontEnd : project1「A社住宅価格予測システム」のtestタブを選択
    activate FrontEnd

    FrontEnd -> BackEnd : GET /Xcorp-Dev/projects/1/tests
    activate BackEnd
    note left
      <Request>
      None
    end note

    BackEnd -> DB : テスト一覧取得
    activate DB
    BackEnd <- DB : テスト一覧
    deactivate DB

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          Tests:
          [
              {
                Id:1,
                Name:"1018_Model_Boston",
                Status:"Complete",
                Result:"OK 2 / NG 1"
              },
              {
                Id:2,
                Name:"1018_Model_NewYork",
                Status:"Complete",
                Result:"OK 5 / NG 0"
              }
          ]
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : test一覧画面
    deactivate FrontEnd
end

group test追加
    User -> FrontEnd : testタブの追加を選択
    activate FrontEnd

    group テンプレートにするリファレンス一覧を取得
        FrontEnd -> BackEnd : GET /Xcorp-Dev/references
        activate BackEnd
        note left
        <Request>
        None
        end note
        BackEnd -> DB : リファレンス一覧取得
        activate DB
        BackEnd <- DB : リファレンス一覧
        deactivate DB
        FrontEnd <- BackEnd : response
        note right
        <Response>
        {
            Result:{
                Code:0,
                Message:"Success"
            },
            References:
            [
                {
                    Id:1,
                    Name:"BasicRegressor"
                }
            ]
        }
        end note
        deactivate BackEnd
    end group

    User <- FrontEnd : test編集画面

    User -> FrontEnd : 画面で作成情報を入力

    FrontEnd -> BackEnd : POST /Xcorp-Dev/projects/1/tests
    activate BackEnd
    note left
      <Request>
      {
          Name:"1018_Model_LosAngeles",
          ReferenceId:1
      }
    end note

    BackEnd -> DB : テスト追加

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          }
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : tests画面
    deactivate FrontEnd

end

group test編集
end

group test複製
end

group test削除
end

10/25 FB　ここまで　'/

group test実行
    User -> FrontEnd : testの「Run Test」を選択
    activate FrontEnd

    FrontEnd -> BackEnd : POST /Xcorp-Dev/projects/1/testDescriotions/runner
    activate BackEnd
    note left
      <Request>
      {
          Command:"AsyncStart"
      }
    end note

    BackEnd -> DB : テスト実行パラメータ取得
    activate DB
    BackEnd <- DB : テスト実行パラメータ
    deactivate DB

    BackEnd -> NoSQLDB : テスト実行アセット取得
    activate NoSQLDB
    BackEnd <- NoSQLDB : テスト実行アセット
    deactivate NoSQLDB

    BackEnd -> DB : テスト実行開始更新

    BackEnd --> TestRunner : テスト起動
    activate TestRunner

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          Job:
          {
              Id:1,
              StartDateTime:"2019-10-25 15:00:00T+0900"
          }
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : tests画面
    deactivate FrontEnd

    BackEnd <-- TestRunner : テスト終了
    deactivate TestRunner
    
    activate BackEnd
        BackEnd -> DB : テスト実行結果更新
        BackEnd -> BackEnd : レポート生成
        activate BackEnd
            BackEnd -> DB : テスト結果取得
            activate DB
            BackEnd <- DB : テスト結果
            deactivate DB

            BackEnd -> BackEnd : レポート生成
            BackEnd -> BackEnd : レポートダウンロードリンク作成
            FrontEnd <- BackEnd : 通知　※実現方法は要検討
        deactivate BackEnd
    deactivate BackEnd

end

group report出力
    User -> FrontEnd : test1の「Generate report」を選択
    activate FrontEnd

    FrontEnd -> BackEnd : GET /Xcorp-Dev/projects/1/tests/1/report
    activate BackEnd
    note left
      <Request>
      None
    end note

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          Report:
          {
              url:"https://XXX"
          }
      }
    end note

    User <- FrontEnd : ダウンロードしたレポートを取得
    deactivate FrontEnd
end

group testDescriptions表示
    User -> FrontEnd : testDescriptionsを選択
    activate FrontEnd

    FrontEnd -> BackEnd : GET /Xcorp-Dev/projects/1/testDescriptions
    activate BackEnd
    note left
      <Request>
      None
    end note

    BackEnd -> DB : テスト取得
    activate DB
    BackEnd <- DB : テスト
    deactivate DB

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          Test:
          {
              Id:1,
              Status:"Complete",
              Result:"OK 2 / NG 1",
              TestDescriptions:
              [
                  {
                      Id:1,
                      Name:"NeuronCoverage",
                      Result:"OK"
                  },
                  {
                      Id:2,
                      Name:"MetamorphicTesting",
                      Result:"OK"
                  },
                  {
                      Id:3,
                      Name:"AttributeCoverage",
                      Result:"NG"
                  }
              ]
          }
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : testDescriptions画面
    deactivate FrontEnd
end

group testDescription表示
    User -> FrontEnd : description1「NeuronCoverage」を選択
    activate FrontEnd

    FrontEnd -> BackEnd : GET /Xcorp-Dev/projects/1/testDescriptions/1
    activate BackEnd
    note left
      <Request>
      None
    end note

    BackEnd -> DB : テストデスクリプション詳細取得
    activate DB
    BackEnd <- DB : テストデスクリプション詳細
    deactivate DB

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          TestDescriptionDetail:
          {
              Id:1,
              Name:"NeuronCoverage",
              Measurment:
              {
                  id:1,
                  Name:"Coverage of activated neurons",
                  Operands:
                  [
                      {
                        Id:1
                        Name:"GoalCoverage",
                        Value:80,
                        Unit:"%"
                      }
                  ]
              },
              TargetAssets:
              [
                  {
                      Id:4,
                      Name:"TestDataset_1018"
                  },
                  {
                      Id:5,
                      Name:"TrainedModel_1007"
                  },
              ],
              TestRunner:
              {
                id:1,
                Name:"neuron_coverage_v3.py",
                Params:[
                    {
                        Id:1,
                        Name:"Threshold",
                        Value:0.5
                    },
                    {
                        Id:2,
                        Name:"Lower Limit",
                        Value:0.3
                    },
                    {
                        Id:3,
                        Name:"Upper Limit",
                        Value:1.0
                    }
                ]
              },
              Result:
              {
                  Summary:"OK",
                  Detail:"Current Coverage 85%",
                  Graph:"http://XXX"
              }
          }
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : testDescription画面
    deactivate FrontEnd
end

group testDescription追加
    User -> FrontEnd : testDescription追加を選択
    activate FrontEnd

    group QualityMeasurement取得
        FrontEnd -> BackEnd : GET /Xcorp-Dev/QualityMeasurements
        activate BackEnd
        note left
        <Request>
        None
        end note

        BackEnd -> DB : QualityMeasurement一覧取得
        activate DB
        BackEnd <- DB : QualityMeasurement一覧
        deactivate DB

        FrontEnd <- BackEnd : response
        note right
        <Response>
        {
            Result:{
                Code:0,
                Message:"Success"
            },
            QualityMeasurements:
            [
                {
                    Id:1,
                    Name:"Coverage of activated neurons",
                    Oprerands:
                    [
                        {
                            Id:1,
                            Name:"GoalCoverage",
                            Type:"Integer",
                            Unit:"%"
                        }
                    ],
                    TaegetAssets:
                    [
                        {
                            Id:1,
                            Name:"TrainedModel"
                        },
                        {
                            Id:2,
                            Name:"CoverageTestData"
                        }
                    ],
                    RunnableTestRunner:
                    {
                        Type:"NeuronCoverage"
                    }
                }
            ]
        }
        end note
        deactivate BackEnd
    end group
    
    group TestRunner取得
        FrontEnd -> BackEnd : GET /Xcorp-Dev/testRunners
        activate BackEnd
        note left
        <Request>
        None
        end note

        BackEnd -> DB : TestRunner一覧取得
        activate DB
        BackEnd <- DB : TestRunner一覧
        deactivate DB

        FrontEnd <- BackEnd : response
        note right
        <Response>
        {
            Result:{
                Code:0,
                Message:"Success"
            },
            TestRunners:
            [
                {
                    Id:1,
                    Type:"NeuronCoverage",
                    Name:"neuron_coverage_v3.py",
                    Params:[
                        {
                            Id:1,
                            Name:"Threshold",
                            Type:"Float"
                        },
                        {
                            Id:2,
                            Name:"Lower Limit",
                            Type:"Float"
                        },
                        {
                            Id:3,
                            Name:"Upper Limit",
                            Type:"Float"
                        }
                    ]
                },
                {
                    Id:2,
                    Type:"NeuronCoverage",
                    Name:"neuron_coverage_ex.py",
                    Params:[
                        {
                            Id:1,
                            Name:"Threshold",
                            Type:"Float"
                        },
                        {
                            Id:2,
                            Name:"Lower Limit",
                            Type:"Float"
                        },
                        {
                            Id:3,
                            Name:"Upper Limit",
                            Type:"Float"
                        }
                    ]
                }
            ]
        }
        end note
        deactivate BackEnd
    end group

    'asset一覧取得'
    FrontEnd -> BackEnd : GET /Xcorp-Dev/projects/1/assets
    activate BackEnd
    FrontEnd <- BackEnd : response
    deactivate BackEnd
    note right
      アセット一覧取得：中略
    end note

    User <- FrontEnd : testDescription編集画面

    User -> FrontEnd : testDescription入力

    FrontEnd -> BackEnd : POST /Xcorp-Dev/projects/1/testDescriptions
    activate BackEnd
    note left
      <Request>
      {
          Name:"Neuron Coverage",
          QualityMeasurement:
          {
              Id:1,
              Operands:
              [
                  {
                      Id:1,
                      Value:60
                  }
              ],
              TargetAssets:
              [
                  {
                      Id:1,
                      AssetId:5
                  },
                  {
                      Id:2,
                      AssetId:4
                  }
              ]
          },
          TestRunner:
          {
            Id:1,
            Params:[
                {
                    Id:1,
                    Value:0.5
                },
                {
                    Id:2,
                    Value:0.3
                },
                {
                    Id:3,
                    Value:1.0
                }
            ]
          }
      }
    end note

    BackEnd -> DB : テストデスクリプション追加

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          }
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : testDescription画面
    deactivate FrontEnd
end

group testDescription編集
    User -> FrontEnd : description1「NeuronCoverage」のEditボタンを選択
    activate FrontEnd

    FrontEnd -> BackEnd : GET /Xcorp-Dev/projects/1/testDescriptions/1
    activate BackEnd
    note left
      <Request>
      None
    end note

    BackEnd -> DB : テストデスクリプション詳細取得
    activate DB
    BackEnd <- DB : テストデスクリプション詳細
    deactivate DB

    FrontEnd <- BackEnd : response
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          },
          TestDescriptionDetail:
          {
              Id:1,
              Name:"NeuronCoverage",
              Measurment:
              {
                  id:1,
                  Name:"Coverage of activated neurons",
                  Operands:
                  [
                      {
                        Id:1
                        Name:"GoalCoverage",
                        Value:80,
                        Unit:"%"
                      }
                  ]
              },
              TargetAssets:
              [
                  {
                      Id:4,
                      Name:"TestDataset_1018"
                  },
                  {
                      Id:5,
                      Name:"TrainedModel_1007"
                  },
              ],
              TestRunner:
              {
                id:1,
                Name:"neuron_coverage_v3.py",
                Params:[
                    {
                        Id:1,
                        Name:"Threshold",
                        Value:0.5
                    },
                    {
                        Id:2,
                        Name:"Lower Limit",
                        Value:0.3
                    },
                    {
                        Id:3,
                        Name:"Upper Limit",
                        Value:1.0
                    }
                ]
              },
              Result:
              {
                  Summary:"OK",
                  Detail:"Current Coverage 85%",
                  Graph:"http://XXX"
              }
          }
      }
    end note
    deactivate BackEnd

    User <- FrontEnd : testDescriptionEdit画面
    deactivate User

    User -> FrontEnd : testDescriptionを登録

    FrontEnd -> BackEnd  : POST /Xcorp-Dev/projects/1/testDescriptionsEdit/1
    deactivate BackEnd
    note left
      <Request>
      {
          TestDescriptionDetail:
          {
              Id:1,
              Name:"NeuronCoverage",
              Measurment:
              {
                  id:1,
                  Name:"Coverage of activated neurons",
                  Operands:
                  [
                      {
                        Id:1
                        Name:"GoalCoverage",
                        Value:80,
                        Unit:"%"
                      }
                  ]
              },
              TargetAssets:
              [
                  {
                      Id:4,
                      Name:"TestDataset_1018"
                  },
                  {
                      Id:5,
                      Name:"TrainedModel_1007"
                  },
              ],
              TestRunner:
              {
                id:1,
                Name:"neuron_coverage_v4.py",
                Params:[
                    {
                        Id:1,
                        Name:"Threshold",
                        Value:0.8
                    },
                    {
                        Id:2,
                        Name:"Lower Limit",
                        Value:0.4
                    },
                    {
                        Id:3,
                        Name:"Upper Limit",
                        Value:1.0
                    }
                ]
              }
          }
      }
    end note
    BackEnd -> DB : testDescriptionを登録
    deactivate DB

    BackEnd <- DB : Response
    deactivate BackEnd

    FrontEnd <- BackEnd : Response
    deactivate FrontEnd
    note right
      <Response>
      {
          Result:{
              Code:0,
              Message:"Success"
          }
      }
    end note
    User <- FrontEnd : testDescription画面
    deactivate User

end

group testDescription複製
end

group testDescription削除
end

group testRunner追加
end

@enduml