@startuml TF2_Testbed

skinparam monochrome true

|User|
start
:TestDescription一覧表示画面に遷移する;
if (ステータスが実行中) then (yes)
  :実行ボタンは非活性;
  stop
endif

:実行ボタンを押下する;

|#AntiqueWhite|Frontend|
:実行ボタンアクション実行;
:[RestAPI]\n POST /:orgID:/projects/:projID:/testDescriotions/runners;

|Backend|
:リクエストパラメータバリデーション;
if (バリデーションエラー?) then (yes)
  :400レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
:(DB-select) 
from
  M_Organization as m_org
  M_Project as m_proj
  T_Test as t_test 
  T_TestDescription as t_testdesc
  M_MeasurementSet as m_measure
  M_TestRunner as m_testrunner
  T_UseAsset as t_useasset
  M_Asset as m_asset
  T_MeasurementParam as t_measure_param
  T_TestRunnerParam as t_testrnner_param
where 
  m_org.id=:orgID: and
  m_proj.id=:projID: and
  t_test.status!=running
join
  m_org on 
    m_org.id==m_proj.org_id and
  m_proj on 
    m_proj.id==t_test.prj_id and
  t_test on 
    t_test.id==t_testdesc.test_id
  m_measure on 
    m_measure.id==t_testdesc.measurementset_id
  m_testrunner on 
    m_testrunner.id==t_testdesc.testrunner_id
  t_useasset on 
    t_useasset.testdesc_id==t_testdesc.id
  m_asset on 
    m_asset.id==t_useasset.asset_id
  t_measure_param on 
    t_measure_param.testdesc_id==t_testdesc.id
  t_testrnner_param on 
    t_testrnner_param.testdesc_id==t_testdesc.id;

|#AntiqueWhite|DB|
:M_Organization
M_Project
T_Test
T_TestDescription
M_MeasurementSet
M_TestRunner
T_UseAsset
M_Asset
T_MeasurementParam
T_TestRunnerParam;

|Backend|
if (DBエラー?) then (yes)
  :500レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
if (:orgID:と:projID:の組み合わせが間違っているか?) then (yes)
  :404レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
:job = create_job();
while (testDescription in testDescriptions)
  :task = create_task(testDescription);
  :job.add_task(task);
endwhile
:regist_result = qai_framework.regist_job(job);

|QAI_Framework|
:job_queue.push(job);

|Backend|
if (regist_result.is_success) then (failed)
  |Backend|
  :500レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
else (success)
  |Backend|
  :(DB-update) 
  from
    M_Organization as m_org
    M_Project as m_proj
    T_Test as t_test 
    T_TestDescription as t_testdesc
  where 
    m_org.id=:orgID: and
    m_proj.id=:projID: and
    m_test.status!=running
  join
    m_org on 
      m_org.id==m_proj.org_id and
    m_proj on 
      m_proj.id==t_test.prj_id and
    t_test on 
      t_test.id==t_testdesc.test_id
  update value
    t_test.status = running
    t_testdesc.status = running;

  |#AntiqueWhite|DB|
  :M_Organization
  M_Project
  T_Test
  T_TestDescription;

  |Backend|
  :200レスポンス作成;
endif

|#AntiqueWhite|Frontend|
:テスト実行ステータス表示更新;

|User|
stop

@enduml