@startuml TF2_Testbed

skinparam monochrome true

|User|
start
:TestDescription一覧表示画面に遷移する;

|#AntiqueWhite|Frontend|
:TestDescription一覧表示画面初期化;
:[RestAPI]\n GET /:orgID:/projects/:projID:/testDescriptions;

|Backend|
:リクエストパラメータバリデーション;
if (バリデーションエラー?) then (yes)
  :400レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
:(DB-select)
from 
  M_Organization as m_org
  M_Project as m_proj
  T_Test as t_test 
  T_TestDescription as t_testdesc
where
  m_org.id=:orgID: and 
  m_proj.id=:projID:
join 
  m_org on 
    m_org.id==m_proj.org_id and
  m_proj on 
    m_proj.id==t_test.prj_id and
  t_test on 
    t_test.id==t_testdesc.test_id;

|#AntiqueWhite|DB|
:M_Organization
M_Project
T_Test
T_TestDescription;

|Backend|
if (DBエラー?) then (yes)
  :500レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
if (:orgID:と:projID:の組み合わせが間違っているか?) then (yes)
  :404レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
:200レスポンス作成;

|#AntiqueWhite|Frontend|
:TestDescription一覧表示画面表示;
note left
  ページング処理はフロントで実装
  必要に応じてページングの結果を返すAPIを用意する
end note

|User|
stop

@enduml