@startuml TF2_Testbed

skinparam monochrome true

|User|
start
:TestDescription詳細表示画面に遷移する;

|#AntiqueWhite|Frontend|
:TestDescription詳細表示画面初期化;
:[RestAPI]\n GET /:orgID:/projects/:projID:/testDescriptions/:testDescId:;

|Backend|
:リクエストパラメータバリデーション;
if (バリデーションエラー?) then (yes)
  :400レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
:(DB-select) 
from
  M_Organization as m_org
  M_Project as m_proj
  T_Test as t_test 
  M_MeasurementSet as m_measure
  M_TestRunner as m_testrunner
  T_UseAsset as t_useasset
  M_Asset as m_asset
  T_MeasurementParam as t_measure_param
  T_TestRunnerParam as t_testrnner_param
  T_TestDescriptionTaskResult as t_testdesc_result
where 
  m_org.id=:orgID: and
  m_proj.id=:projID: and
  t_testdesc.id=:testDescId:
join
  m_org on 
    m_org.id==m_proj.org_id and
  m_proj on 
    m_proj.id==t_test.prj_id and
  t_test on 
    t_test.id==t_testdesc.test_id
  m_measure on 
    m_measure.id==t_testdesc.measurementset_id
  m_testrunner on 
    m_testrunner.id==t_testdesc.testrunner_id
  t_useasset on 
    t_useasset.testdesc_id==t_testdesc.id
  m_asset on 
    m_asset.id==t_useasset.asset_id
  t_measure_param on 
    t_measure_param.testdesc_id==t_testdesc.id
  t_testrnner_param on 
    t_testrnner_param.testdesc_id==t_testdesc.id
  t_testdesc_result on 
    t_testdesc_result.testdesc_id==t_testdesc.id;

|#AntiqueWhite|DB|
:M_Organization
M_Project
T_Test
T_TestDescription
M_MeasurementSet
M_TestRunner
T_UseAsset
M_Asset
T_MeasurementParam
T_TestRunnerParam
T_TestDescriptionTaskResult;

|Backend|
if (DBエラー?) then (yes)
  :500レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
if (:orgID:と:projID:と:testDescID:の組み合わせが間違っているか?) then (yes)
  :404レスポンス作成;
  |#AntiqueWhite|Frontend|
  :エラー表示;
  |User|
  stop
endif

|Backend|
:200レスポンス作成;

if (実行完了済み かつ 表示アセットあり?) then (yes)
  |NoSQLDB|
  :実行結果ログ取得?;
  note left
    T.B.D
    どういったアセットを画面に表示するかは未検討
    ログであればダウンロードリンクを返すだけでもいいか
  end note
endif

|#AntiqueWhite|Frontend|
:TestDescription詳細表示画面表示;

|User|
stop

@enduml