version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev2_aitdev"
    schedule:
      interval: 'daily'
      time: "07:00"
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev2_aithub"
    schedule:
      interval: 'daily'
      time: "07:00"
