version: '3'
services:
  reverse-proxy:
    image: reverse-proxy-resty
    ports:
      - 8888:80
    container_name: reverse-proxy-resty
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
