FROM python:3.9.13

ENV PROJECT_ROOTDIR /work/

WORKDIR $PROJECT_ROOTDIR

COPY ./libs/ $PROJECT_ROOTDIR/libs

COPY constraints.txt $PROJECT_ROOTDIR

RUN pip install -U pip && \
    pip install -r constraints.txt