version: "3"

services:
  ip:
    build:
      context: .
      dockerfile: Dockerfile
    image: integration-provider
    container_name: ip
    ports: 
      - ${FLASK_PORT}:${FLASK_PORT}
    expose: 
      - ${FLASK_PORT}
    environment:
      - FLASK_PORT=${FLASK_PORT}
      - FLASK_CONFIG=${FLASK_CONFIG}
    volumes:
      - ./:/work/
    command: 
      ['python', '-m', 'entrypoint', 'startserver']