FROM python:3.6.8

# To SET DB initialize disable
# True/False
ENV QAI_TB_INIT_DB False

# there is need setup when QAI_TB_INIT_DB is True
# To SET DB initialize in host file system
# windows:WINDOWS_FILE
# other:UNIX_FILE_SYSTEM
ENV QAI_HOST_FILE_SYSTEM WINDOWS_FILE

# there is need setup when QAI_TB_INIT_DB is True
# To SET DB initialize in dockerfile exists dir
ENV QAI_HOST_DIR C:\\m-akita\\github\\qai-testbed\\src\\backend

# backendセットアップ
ENV DEBIAN_FRONTEND noninteractive
ENV PROJECT_ROOTDIR /work/
WORKDIR $PROJECT_ROOTDIR
COPY requirements.txt $PROJECT_ROOTDIR

# pip install ReportGenerator モジュールのセットアップ準備
COPY ./report/ $PROJECT_ROOTDIR/report

COPY ./libs/ $PROJECT_ROOTDIR/libs

# モジュールのセットアップ
RUN pip install -U pip && \
    pip install -r requirements.txt
## wkhtmltopdfのセットアップ
### wkhtmltopdfに必要なアプリをインストール
RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      xorg \
      libssl-dev \
      libxrender-dev \
      wget \
      unzip \
      gdebi \
      fonts-noto-cjk \
      emacs && \
    apt-get autoremove && \
    apt-get clean && \
    fc-cache -fv
### wkhtmltopdf本体のインストール(このインストーラーはdebian9.x系しか動きません)
WORKDIR /opt
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
RUN apt install ./wkhtmltox_0.12.5-1.stretch_amd64.deb

# mound root dir
RUN mkdir /testbed_mount_volume_dst /testbed_mount_volume_dst/report

WORKDIR $PROJECT_ROOTDIR