FROM python:3.6-slim-stretch
LABEL maintainer="AIST"

ENV QAI_USER=qai
ENV QAI_HOME=/usr/local/${QAI_USER}
ENV QAI_USER_HOME=${QAI_HOME}

# Never prompts the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

# # Define en_US.
# ENV LANGUAGE en_US.UTF-8
# ENV LANG en_US.UTF-8
# ENV LC_ALL en_US.UTF-8
# ENV LC_CTYPE en_US.UTF-8
# ENV LC_MESSAGES en_US.UTF-8

# Define ja_JP.
RUN apt-get update -yqq \
    && apt-get install locales -yqq \
    && echo "ja_JP UTF-8" > /etc/locale.gen \
    && locale-gen
ENV LANGUAGE ja_JP:ja
ENV LANG ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
ENV LC_CTYPE ja_JP.UTF-8
ENV LC_MESSAGES ja_JP.UTF-8

COPY ./repository/dummy_result_data ${QAI_USER_HOME}/dummy_result_data
COPY ./repository/entrypoint.py ${QAI_USER_HOME}/entrypoint.py
COPY ./repository/requirements.txt ${QAI_USER_HOME}/requirements.txt

RUN pip install -r ${QAI_USER_HOME}/requirements.txt \
    && rm ${QAI_USER_HOME}/requirements.txt

# mound root dir
# RUN mkdir ${QAI_USER_HOME}/args ${QAI_USER_HOME}/result ${QAI_USER_HOME}/inventory

RUN useradd -m ${QAI_USER} \
    && chown -R ${QAI_USER} ${QAI_USER_HOME}
USER ${QAI_USER}
WORKDIR ${QAI_USER_HOME}
# mound root dir
RUN mkdir ./args ./result ./inventory

ENTRYPOINT [ "python", "entrypoint.py" ]
# CMD ["/bin/bash"]