# QAI Testbed backend REST API Test script
# REST Client URL:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostUrl = http://127.0.0.1:5000
@baseUrl = {{hostUrl}}/qai-testbed/api/0.0.1

###
# API:health-check

GET {{baseUrl}}/health-check

###
# API: POST /login
POST {{baseUrl}}/login
content-type: application/json

{
    "AccountId": "mail",
    "Password": "pass"
}
###
# API: MLFrameworks
GET {{baseUrl}}/mlFrameworks

###
# API: GET /mlComponents
GET {{baseUrl}}/dep-a/mlComponents

###
# API: POST /mlComponents
POST {{baseUrl}}/dep-a/mlComponents
content-type: application/json

{
    "Name": "Fashion Classifier",
    "Description": "Fashion image classification",
    "ProblemDomain": "Image Classification",
    "MLFrameworkId": 1,
    "GuidelineId": 1,
    "ScopeId": 1,
    "GuidelineReason": "This guideline fits the project",
    "ScopeReason": "This scope fits the project"
}

###
# API: POST /mlComponents
PUT {{baseUrl}}/dep-a/mlComponents/1
content-type: application/json

{
    "Name": "Fashion Classifier_2",
    "Description": "Fashion image classification_2",
    "ProblemDomain": "Image Classification_2",
    "MLFrameworkId": 1,
    "GuidelineId": 1,
    "ScopeId": 1,
    "GuidelineReason": "This guideline fits the project",
    "ScopeReason": "This scope fits the project"
}

###
# API: DELETE mlComponents
DELETE {{baseUrl}}/dep-a/mlComponents/1

###
# API: PUT /<OrganizerId>/mlComponents/<mlComponentsId>/report_opinion
PUT {{baseUrl}}/dep-a/mlComponents/1/report_opinion
content-type: application/json

{
    "ReportOpinion": "All TDs meet the requirements"
}

###
# API: POST testDescriotions
POST {{baseUrl}}/dep-a/mlComponents/1/testDescriotions
content-type: application/json

{
    "Name": "Neuron Coverage",
    "QualityDimensionID": 5,
    "ParentID": 1,
    "QualityMeasurements": [
        {"Id":1, "Value":"60", "RelationalOperatorId":1, "Enable": true}
    ],
    "TargetInventories": [
        {"Id":1, "InventoryId": 1, "TemplateInventoryId": 1},
        {"Id":2, "InventoryId": 2, "TemplateInventoryId": 2}
    ],
    "TestRunner": {
        "Id":1,
        "Params":[
            {"TestRunnerParamTemplateId":1, "Value":"0.5"},
            {"TestRunnerParamTemplateId":2, "Value":"0.3"},
            {"TestRunnerParamTemplateId":3, "Value":"1.0"}
        ]
    }
}

###
# API: PUT testDescriotions
PUT {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/4
content-type: application/json

{
    "Name": "Neuron Coverage2",
    "QualityDimensionID": 5,
    "QualityMeasurements": [
        {"Id":1, "Value":"70", "RelationalOperatorId":1, "Enable": false}
    ],
    "TargetInventories": [
        {"Id":1, "InventoryId": 1, "TemplateInventoryId": 1},
        {"Id":2, "InventoryId": 6, "TemplateInventoryId": 2}
    ],
    "TestRunner": {
        "Id":1,
        "Params":[
            {"TestRunnerParamTemplateId":1, "Value":"0.6"},
            {"TestRunnerParamTemplateId":2, "Value":"0.4"},
            {"TestRunnerParamTemplateId":3, "Value":"1.0"}
        ]
    }
}

###
# API: PUT testDescriotions change AIT
PUT {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/4
content-type: application/json

{
    "Name": "Neuron CoverageX",
    "QualityDimensionID": 6,
    "QualityMeasurements": [
        {"Id":2, "Value":"1.5", "RelationalOperatorId":1, "Enable": true}
    ],
    "TargetInventories": [
        {"Id":1, "InventoryId": 3, "TemplateInventoryId": 3},
        {"Id":2, "InventoryId": 4, "TemplateInventoryId": 4},
        {"Id":3, "InventoryId": 5, "TemplateInventoryId": 5}
    ],
    "TestRunner": {
        "Id":2,
        "Params":[
            {"TestRunnerParamTemplateId":4, "Value":"select"},
            {"TestRunnerParamTemplateId":5, "Value":"1"},
            {"TestRunnerParamTemplateId":6, "Value":"balance"},
            {"TestRunnerParamTemplateId":7, "Value":"test"},
            {"TestRunnerParamTemplateId":8, "Value":"attacks"},
            {"TestRunnerParamTemplateId":9, "Value":"robustness"},
            {"TestRunnerParamTemplateId":10, "Value":"detection"}
        ]
    }
}

###
# API: DELETE testDescriotions
DELETE {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/1

###
# API: testDescriotions/runners
POST {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/runners
content-type: application/json

{
    "Command": "AsyncStart",
    "TestDescriptionIds": [3]
}

###
# API: testDescriotions/run-status
GET {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/run-status

###
# API: testDescriotions
GET {{baseUrl}}/dep-a/mlComponents/1/testDescriotions

###
# API: testDescriotionDetail
GET {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/3

###
# API: testDescriotion Star
POST {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/1/star

###
# API: testDescriotion UnStar
POST {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/1/unstar

###
# API: testDescriotion ancestors
GET {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/1/ancestors

###
# API: testDescriotions/reportGenerator(set param)
POST {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/reportGenerator
content-type: application/json

{
    "Command": "SetParam",
    "Destination": ["3"],
    "Params": {
        "Opinion": "精度について問題なし。",
        "Graphs": [
            {"GraphId": 1, "ReportRequired": true, "ReportIndex": 4, "ReportName": "Graph-A"},
            {"GraphId": 2, "ReportRequired": true, "ReportIndex": 3, "ReportName": "Graph-B"},
            {"GraphId": 3, "ReportRequired": true, "ReportIndex": 2, "ReportName": "Graph-C"},
            {"GraphId": 4, "ReportRequired": true, "ReportIndex": 1, "ReportName": "Graph-D"}
        ]
    }
}

###
# API: testDescriotions/reportGenerator(set param)
POST {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/reportGenerator
content-type: application/json

{
    "Command": "SetParam",
    "Destination": ["3"],
    "Params": {
        "Opinion": "精度について問題なし。",
        "Graphs": [
            {"GraphId": 1, "ReportRequired": true, "ReportIndex": 4, "ReportName": "Graph-A"},
            {"GraphId": 2, "ReportRequired": false, "ReportIndex": 3, "ReportName": "Graph-B"},
            {"GraphId": 3, "ReportRequired": false},
            {"GraphId": 4, "ReportRequired": true, "ReportIndex": 1, "ReportName": "Graph-D"}
        ]
    }
}

###
# API: testDescriotions/reportGenerator(report generate)
POST {{baseUrl}}/dep-a/mlComponents/1/testDescriotions/reportGenerator
content-type: application/json

{
    "Command": "Generate",
    "Destination": ["3"]
}

###
# API: GET QualityMeasurements
GET {{baseUrl}}/QualityMeasurements

###
# API: POST QualityMeasurements
POST {{baseUrl}}/QualityMeasurements
content-type: application/json

{
  "Name": "分類問題における学習モデルACC計測",
  "Version": "0.1",
  "Description": "ACC = (TP+TF) / (TP+FP+TN+FN)",
  "QualityDimensionId": 5,
  "OperandTemplates": [
  {
      "Name": "ACC",
      "Unit": "%"
  }]
}

###
# API: GET QualityMeasurements/RelationalOperators
GET {{baseUrl}}/QualityMeasurements/RelationalOperators

###
# API: download
GET {{baseUrl}}/download/1

###
# API: format
GET {{baseUrl}}/formats

###
# API: inventories
GET {{baseUrl}}/dep-a/mlComponents/1/inventories

###
# API: POST inventories
POST {{baseUrl}}/dep-a/mlComponents/1/inventories
content-type: application/json

{
  "Name": "Testdata",
  "TypeId": 1,
  "FileSystemId": 1,
  "FilePath": "/mnt/xxx/99",
  "Description": "テスト用のデータ",
  "Formats": [
    "csv",
    "dump"
  ]
}

###
# API: DELETE inventories
DELETE {{baseUrl}}/dep-a/mlComponents/1/inventories/1

###
# API: PUT inventories
PUT {{baseUrl}}/dep-a/mlComponents/1/inventories/1
content-type: application/json

{
  "Name": "Testdata99",
  "TypeId": 2,
  "FileSystemId": 2,
  "FilePath": "/mnt/xxx/99",
  "Description": "テスト99用のデータ",
  "Formats": [
    "csv",
    "zip"
  ]
}

###
# API: dataTypes
GET {{baseUrl}}/dataTypes

###
# API: fileSystems
GET {{baseUrl}}/fileSystems

###
# API: GET test runners
GET {{baseUrl}}/testRunners

###
# API: POST AIT manifest
POST {{baseUrl}}/testRunners
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ait.manifest"; filename="ait.manifest.json"
Content-Type: application/json

< ./test_res/ait.manifest.json
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# API: DELETE AIT manifest
DELETE  {{baseUrl}}/testRunners/4

###
# API: roles
# TODO ロール関連の実装は保留とするため、一旦コメントアウト
# GET {{baseUrl}}/roles

###
# API: users
# TODO ユーザ関連の実装は保留とするため、一旦コメントアウト
# GET {{baseUrl}}/users

###
# API: GET guidelines
GET {{baseUrl}}/guidelines

###
# API: POST guidelines
POST {{baseUrl}}/guidelines
content-type: application/json

{
    "AithubGuidelineId": 2,
    "Name": "Guideline_01",
    "Description": "Guideline_01 ",
    "Creator": "Guideline_01_Members",
    "Publisher": "AIST",
    "Identifier": "https://www.digiarc.aist.go.jp/publication/aiqm/AIQM-Guideline-2.1.0.pdf",
    "PublishDatetime": "2021-04-01 01:23:45",
    "CreationDatetime": "2021-04-01 01:23:45"
}

###
# API: DELETE guideline
DELETE {{baseUrl}}/guideline/3

###
# API: PUT guidelines
PUT {{baseUrl}}/guideline/2
content-type: application/json

{
    "Description": "Guideline_01_update",
    "Creator": "Guideline_01_Members_update",
    "Publisher": "AIST_update",
    "Identifier": "https://www.digiarc.aist.go.jp/publication/aiqm/AIQM-Guideline-2.1.0.pdf",
    "PublishDatetime": "2022-06-14 11:23:45",
    "AIThubDeleteFlag": true
}


###
# API: GET scopes
GET {{baseUrl}}/scopes

###
# API: GET /guidelines/{GuidelineId}/scopes
GET {{baseUrl}}/guidelines/1/scopes

###
# API: GET /guidelines/{GuidelineId}/scope_quality_dimensions
GET {{baseUrl}}/guidelines/1/scope_quality_dimensions

###
# API: GET /scopes/{ScopeId}/quality_dimensions
GET {{baseUrl}}/scopes/1/quality_dimensions

###
# API: GET /guidelines/{GuidelineId}/quality_dimensions
GET {{baseUrl}}/guidelines/1/quality_dimensions

###
# API: GET /qualityDimensions/{GuidelineName}/{QualityDimensionName}
GET {{baseUrl}}/qualityDimensions/AIQM_Guideline/Completeness_of_problem_domain_analysis

###
# API: Organizers
# TODO 組織関連の実装は保留とするため、一旦コメントアウト
# GET {{baseUrl}}/organizers

###
# API: GET /mlComponents
GET {{baseUrl}}/testRunners/1/usingTD

###
# API: GET /reportTemplates
GET {{baseUrl}}/reportTemplates

###
# API: POST /reportTemplates
POST {{baseUrl}}/reportTemplates
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary_post_reportTemplates

------WebKitFormBoundary_post_reportTemplates
Content-Disposition: form-data; name="Name"
Content-Type: text/plain

test_name
------WebKitFormBoundary_post_reportTemplates
Content-Disposition: form-data; name="GidelineId"
Content-Type: text/plain

1
------WebKitFormBoundary_post_reportTemplates
Content-Disposition: form-data; name="File"; filename="report_template_test.zip"
Content-Type: application/zip

< ./test_res/report_template_test.zip
------WebKitFormBoundary_post_reportTemplates--

###
# API: POST /reportTemplates
POST {{baseUrl}}/reportTemplates/generate
content-type: application/json

{
    "GuidelineId": "1"
}

###
# API: GET /reportTemplates
GET {{baseUrl}}/reportTemplates/1/zip

###
# API: GET /ait_local
GET {{baseUrl}}/ait_local

###
# API: POST /ait_local
POST {{baseUrl}}/ait_local
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary_post_ait_local

------WebKitFormBoundary_post_ait_local
Content-Disposition: form-data; name="ait_zip"; filename="ait_local_eval_coverage_ca_pairwise_0.1.zip"
Content-Type: application/zip

< ./test_res/ait_local_eval_coverage_ca_pairwise_0.1.zip
------WebKitFormBoundary_post_ait_local--

###
# API: GET /guidelines/{guideline_id}/guideline_schema_file
GET {{baseUrl}}/guidelines/3/guideline_schema_file

###
# API: POST /guidelines/guideline_schema_file
POST {{baseUrl}}/guidelines/guideline_schema_file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary_post_guideline_schema_file

------WebKitFormBoundary_post_guideline_schema_file
Content-Disposition: form-data; name="guideline_schema"; filename="guideline.json"
Content-Type: application/json

< ./test_res/guideline.json
------WebKitFormBoundary_post_guideline_schema_file--

###
# API: PUT /guidelines/{guideline_id}/guideline_schema_file
PUT {{baseUrl}}/guidelines/3/guideline_schema_file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary_put_guideline_schema_file

------WebKitFormBoundary_put_guideline_schema_file
Content-Disposition: form-data; name="guideline_schema"; filename="guideline_update.json"
Content-Type: application/json

< ./test_res/guideline_update.json
------WebKitFormBoundary_put_guideline_schema_file--

###
# API: DELETE /guidelines/{guideline_id}/guideline_schema_file
DELETE {{baseUrl}}/guidelines/3/guideline_schema_file

###
# API: GET /guidelines/{guideline_id}/guideline_schema_file/edit_check
GET {{baseUrl}}/guidelines/3/guideline_schema_file/edit_check
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary_put_guideline_schema_file

------WebKitFormBoundary_put_guideline_schema_file
Content-Disposition: form-data; name="guideline_schema"; filename="guideline_update.json"
Content-Type: application/json

< ./test_res/guideline_update.json
------WebKitFormBoundary_put_guideline_schema_file--

###
# API: GET /guidelines/{guideline_id}/guideline_schema_file/delete_check
GET {{baseUrl}}/guidelines/3/guideline_schema_file/delete_check

###
# API: GET /setting/{key}
GET {{baseUrl}}/setting/aithub_linkage_flag

###
# API: PUT /setting/{key}
PUT {{baseUrl}}/setting/aithub_linkage_flag
content-type: application/json

{
    "Value": "0"
}
