FROM jupyter/minimal-notebook

USER root

RUN apt-get update && apt-get install -y \
    curl \
    tree \
    vim

# RUN pip install --upgrade pip
RUN pip3 install --upgrade pip setuptools \
    && pip3 install jupyterlab \
    && jupyter serverextension enable --py jupyterlab

# 作業ディレクトリを指定
WORKDIR /workdir

# コンテナ側のポート番号
EXPOSE 8888

USER jovyan

ENTRYPOINT ["jupyter-lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]

# Jupyterlabのルートとなるディレクトリを指定
CMD ["--notebook-dir=/workdir"]
