FROM python:3.6-slim-stretch
LABEL maintainer="AIST"

ENV QAI_USER=qai
ENV QAI_HOME=/usr/local/${QAI_USER}
ENV QAI_USER_HOME=${QAI_HOME}

ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8

WORKDIR ${QAI_USER_HOME}

RUN mkdir ./args ./result ./inventory

COPY ./requirements.txt /temp/requirements.txt
COPY ./runnertools /temp/runnertools

RUN pip install -U pip && \
    pip install -r /temp/requirements.txt && \
    pip install /temp/runnertools && \
    rm -r /temp
