@startuml erdiagram

skinparam monochrome true

package "UserArea" <<rectangle>>{
    entity "System"
    entity "SubSystem"
    entity "Component"
    entity "AIComponent"
    System --|{ SubSystem
    SubSystem --|{ Component
    Component ||--|| AIComponent
}

package "TestbedArea" <<rectangle>>{
    package "NoSQLDB" as ext <<Database>> {
        entity "Store" {
            asset_store_id
            log_store_id
            visualize_store_id
            report_store_id
        }
    }

    package "QualityTemplateArea" <<rectangle>>{

        entity "M_TestRunner" {
            + id [PK] : integer
            ==
            name : character varying
            description : character varying
            source_repository : character varying
            version : character varying
            create_user_account : character varying
            create_user_name : character varying 
            quality : character varying
            keywords : character varying
            licenses : character varying
            landing_page : character varying
            install_mode : character varying
            install_status : character varying
            delete_flag : boolean
        }

        entity "M_TestRunnerReference" {
            + id [PK] : integer
            ==
            # test_runner_id [FK(M_TestRunner.id)] : integer
            bib_info : character varying
            additional_info : character varying
            url_ : character varying
        }

        entity "M_TestRunnerParamTemplate" {
            + id_ [PK] : integer
            ==
            # test_runner_id [FK(M_TestRunner.id)] : integer
            name : character varying
            value_type : character varying
            description : character varying
            default_value : character varying
            min_value : double precision
            max_value : double precision
            depends_on_parameter : character varying
        }

        entity "M_TestInventoryTemplate" {
            + id_ [PK] : integer
            ==
            # test_runner_id [FK(M_TestRunner.id)] : integer
            # type_id [FK(M_DataType.id)] : integer
            name : character varying
            description : character varying
            depends_on_parameter : character varying
            min: integer
            max: integer
        }

        entity "M_TestInventoryTemplate_Format" {
            + id [PK] : integer
            ==
            # inventory_template_id [FK(M_TestInventoryTemplate.id_)] : integer
            # format_id [FK(M_Format.id)] : integer
        }

        entity "M_TestInventoryTemplate_Compatible_Package" {
            + id [PK] : integer
            ==
            # inventory_template_id [FK(M_TestInventoryTemplate.id_)] : integer
            name : character varying
            version : character varying
            additional_info : character varying
        }

        entity "M_TestInventoryTemplate_Additional_Info" {
            + id [PK] : integer
            ==
            # inventory_template_id [FK(M_TestInventoryTemplate.id_)] : integer
            key : character varying
            value : character varying
        }

        entity "M_TestInventoryTemplateTag" {
            + id [PK] : integer
            ==
            # inventory_template_id [FK(M_TestInventoryTemplate.id_)] : integer
            # tag_id [FK(M_Tag.id)] : integer
        }

        entity "M_Guideline" {
            + id [PK] : integer
            ==
            aithub_guideline_id : integer
            name : character varying
            description : character varying
            creator : character varying
            publisher : character varying
            identifier : character varying
            publish_datetime : timestamp without time zone
            aithub_delete_flag: boolean
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            delete_flag : boolean
        }

        entity "M_Guideline_Schema_File" {
            + id [PK] : integer
            ==
            # guideline_id [FK(M_Guideline.id)] : integer
            name : character varying
            guideline_schema_file = sa.Column(sa.String, nullable=False)
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            delete_flag : boolean
        }

        entity "M_Scope" {
            + id [PK] : integer
            ==
            # guideline_id [FK(M_Guideline.id)] : integer
            aithub_scope_id : integer
            name : character varying
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            delete_flag : boolean
        }

        entity "M_Scope_QualityDimension" {
            + id [PK] : integer
            ==
            # guideline_id [FK(M_Guideline.id)] : integer
            # scope_id [FK(M_Scope.id)] : integer
            # quality_dimension_id [FK(M_Quality_Dimension.id)] : integer
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            delete_flag : boolean
        }

        entity "M_Quality_Dimension" {
            + id [PK] : integer
            ==
            aithub_quality_dimension_id: integer
            # guideline_id [FK(M_Guideline.id)] : integer
            json_id : character varying
            name : character varying
            description : character varying
            sub_dimensions : character varying
            url : character varying
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            delete_flag : boolean
        }

        entity "M_Quality_Dimension_Level" {
            + id [PK] : integer
            ==
            # quality_dimension_id [FK(M_Quality_Dimension.id)] : integer
            quality_dimension_level_id: character varying
            name : character varying
            description : character varying
            level : Float
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            delete_flag : boolean
        }

        entity "M_Quality_Measurement" {
            + id [PK] : integer
            ==
            # structure_id [FK(M_Structure.id)] : integer
            # test_runner_id [FK(M_TestRunner.id)] : integer
            name : character varying
            description : character varying
            type : character varying
            min_value : double precision
            max_value : double precision
        }

        entity "M_GraphTemplate" {
            + id [PK] : integer
            ==
            # test_runner_id [FK(M_TestRunner.id)] : integer
            # resource_type_id [FK(M_ResourceType.id)] : integer
            name : character varying
            description : character varying
        }

        entity "M_Downloadable_Template" {
            + id [PK] : integer
            ==
            # test_runner_id [FK(M_TestRunner.id)] : integer
            name : character varying
            description : character varying
        }

        entity "M_ReportTemplate" {
            + id [PK] : integer
            ==
            # guideline_id [FK(M_Guideline.id)] : integer
            name : character varying
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
        }

        M_Quality_Dimension --|{ M_Quality_Dimension_Level
        M_Quality_Measurement --|{ M_TestRunner
        M_TestRunner --|{ M_TestRunnerReference
        M_TestRunner --|{ M_TestRunnerParamTemplate
        M_TestRunner --|{ M_GraphTemplate
        M_TestRunner --|{ M_TestInventoryTemplate
        M_TestInventoryTemplate -- M_TestInventoryTemplate_Format
        M_TestInventoryTemplate -- M_TestInventoryTemplate_Compatible_Package
        M_TestInventoryTemplate -- M_TestInventoryTemplate_Additional_Info
        M_TestInventoryTemplate -- M_TestInventoryTemplateTag
        M_TestRunner --|{ M_Downloadable_Template
        M_Guideline --|{ M_Quality_Dimension
        M_Guideline --|{ M_ReportTemplate
        M_Guideline --|{ M_Scope
        M_Scope --|{ M_Scope_QualityDimension
        M_Scope_QualityDimension --|{ M_Quality_Dimension
    }

    package "BasicArea" <<rectangle>>{
        entity "M_Organization" {
            + id [PK] : integer
            ==
            organizer_id : character varying
            name : character varying
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            delete_flag : boolean
        }

        entity "M_User" {
            + id [PK] : integer
            ==
            # org_id [FK(M_Organization.id)] : integer
            account_id : character varying
            user_name : character varying
            password_hash : character varying
            delete_flag : boolean
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
        }

        entity "M_Role" {
            + id [PK] : integer
            ==
            name : character varying
        }

        entity "M_User_Role_MLComponent" {
            + id [PK] : integer
            ==
            # user_id [FK(M_User.id)] : integer
            # role_id [FK(M_Role.id)] : integer
            # ml_component_id [FK(M_MLComponent.id)] : integer
            delete_flag : boolean
        }

        entity "M_Inventory" {
            + id [PK] : integer
            ==
            # ml_component_id [FK(M_MLComponent.id)] : integer
            # type_id [FK(M_DataType.id)] : integer
            # file_system_id [FK(M_FileSystem.id)] : integer
            name : character varying
            file_path : character varying
            description : character varying
            delete_flag : boolean
            schema : character varying
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            file_hash_sha256 : character varying
        }

        entity "M_Inventory_Format" {
            + id [PK] : integer
            ==
            # inventory_id [FK(M_Inventory.id)] : integer
            # format_id [FK(M_Format.id)] : integer
        }

        entity "M_Tag" {
            + id [PK] : integer
            ==
            name : character varying
            type : character varying
        }

        entity "M_Setting" {
            + key [PK] : character varying
            ==
            value : character varying
        }

        entity "M_Format" {
            + id [PK] : integer
            ==
            format_ : character varying
        }

        entity "M_Structure" {
            + id [PK] : integer
            ==
            structure : character varying
        }

        entity "M_RelationalOperator" {
            + id [PK] : integer
            ==
            expression : character varying
            description : character varying
        }

        entity "M_MLComponent" {
            + id [PK] : integer
            ==
            # org_id[FK(M_Organization.id)] : integer
            # ml_framework_id[FK(M_MLFrameworkMapper.id)] : integer
            # guideline_id[FK(M_Guideline.id)] : integer
            # scope_id[FK(M_Guideline.id)] : integer
            name : character varying
            description : character varying
            problem_domain : character varying
            guideline_reason : character varying
            scope_reason : character varying
            report_opinion : character varying
            delete_flag : boolean
        }

        entity "M_MLFrameworkMapper" {
            + id : integer
            ==
            name : character varying
        }

        entity "M_ResourceType" {
            + id : integer
            ==
            type : character varying
        }

        entity "M_FileSystem" {
            + id : integer
            ==
            name : character varying
        }

        entity "M_DataType" {
            + id [PK] : integer
            ==
            name : character varying
        }

        M_Organization --|{ M_MLComponent
        M_MLFrameworkMapper --|{ M_MLComponent
        M_MLComponent --|{ M_Inventory
        M_DataType --|{ M_Inventory
        M_FileSystem --|{ M_Inventory
        M_Inventory --|{ M_Inventory_Format
        M_Inventory_Format }|-- M_Format
        M_Organization --|{ M_User
        M_User --|{ M_User_Role_MLComponent
        M_Role --|{ M_User_Role_MLComponent
        M_User_Role_MLComponent --|{ M_User_Role_MLComponent
        M_Guideline --|{ M_MLComponent
        M_Guideline -- M_Guideline_Schema_File
        M_Scope --|{ M_MLComponent

    }

    package "QualityManagementArea" <<rectangle>>{

        entity "T_Test" {
            + id [PK] : integer
            ==
            # ml_component_id [FK(M_MLComponent.id)] : integer
            # job_id [FK(T_Job.id)] : integer
            report_url : character varying
        }

        entity "T_TestDescription" {
            + id [PK] : integer
            ==
            # test_id [FK(T_Test.id)] : integer
            # quality_dimension_id [FK(M_Quality_Dimension.id)] : integer
            # test_runner_id [FK(M_TestRunner.id)] : integer
            # parent_id [FK(T_TestDescription.id)] : integer
            # run_id [FK(T_Run.id)] : integer
            name : character varying
            creation_datetime : timestamp without time zone
            update_datetime : timestamp without time zone
            opinion : character varying
            delete_flag : boolean
            value_target : boolean
            star : boolean
        }

        entity "T_Inventory_TestDescription" {
            + id [PK] : integer
            ==
            # inventory_id [FK(M_Inventory.id)] : integer
            # test_description_id [FK(T_TestDescription.id)] : integer
            # template_inventory_id [FK(M_TestInventoryTemplate.id_)] : integer
        }

        entity "T_TestRunnerParam" {
            + id [PK] : integer
            ==
            # test_runner_param_template_id [FK(M_TestRunnerParamTemplate.id_)] : integer
            # test_description_id [FK(T_TestDescription.id)] : integer
            value : character varying
        }

        entity "T_Operand"{
            + id [PK] : integer
            ==
            # quality_measurement_id [FK(M_Quality_Measurement.id)] : integer
            # test_description_id [FK(T_TestDescription.id)] : integer
            # relational_operator_id [FK(M_RelationalOperator.id)] : integer
            value : character varying
            enable : boolean
        }

        entity "T_Graph"{
            + id [PK] : integer
            ==
            # graph_template_id [FK(M_GraphTemplate.id)] : integer
            # run_id [FK(T_Run.id)] : integer
            # download_id [FK(T_Download.id)] : integer
            report_required : boolean
            graph_address : character varying
            report_index : integer
            report_name : character varying
            file_name : character varying
        }

        entity "T_Download"{
            + id [PK] : integer
            ==
            path : character varying
        }

        entity "T_Downloadable_Data"{
            + id [PK] : integer
            ==
            # run_id [FK(T_Run.id)] : integer
            # downloadable_template_id [FK(M_Downloadable_Template.id)] : integer
            # download_id [FK(T_Download.id)] : integer
            download_address : character varying
            file_name : character varying
        }

        entity "T_Job"{
            + id [PK] : integer
            ==
            status : character varying
            result : character varying
            result_detail : character varying
            creation_datetime : timestamp without time zone
            test_id : integer
        }

        entity "T_Run"{
            + id [PK] : integer
            ==
            # job_id [FK(T_Job.id)] : integer
            status : character varying
            result : character varying
            result_detail : character varying
            cpu_brand : character varying
            cpu_arch : character varying
            cpu_clocks : character varying
            cpu_cores : character varying
            memory_capacity : character varying
            launch_datetime : timestamp without time zone
            done_datetime : timestamp without time zone
            execution_date : character varying
            ait_output_file : character varying
            log_file : character varying
            test_description_id : integer
            error_code : character varying
        }

        entity "T_RunMeasure"{
            + id [PK] : integer
            ==
            # run_id [FK(T_Run.id)] : integer
            measure_name : character varying
            measure_value : double precision
        }

        M_MLComponent -- T_Test
        T_Job -- T_Test
        T_Test --|{ T_TestDescription
        T_TestDescription --|{ T_Operand
        T_TestDescription --|{ T_TestRunnerParam
        T_TestRunnerParam }|-- M_TestRunnerParamTemplate
        T_Graph -- M_GraphTemplate
        T_Run --|{ T_Graph
        T_Graph -- T_Download
        T_TestDescription --|{ T_Inventory_TestDescription
        M_Inventory --|{ T_Inventory_TestDescription
        M_Tag --|{ M_TestInventoryTemplateTag
        M_Format --|{ M_TestInventoryTemplate_Format
        T_Job --|{ T_Run
        T_TestDescription --|{ T_Run
        M_RelationalOperator --|{ T_Operand
        M_Structure --|{ M_Quality_Measurement
        M_ResourceType --|{ M_GraphTemplate
        M_DataType --|{ M_TestInventoryTemplate
        T_TestDescription -- T_TestDescription
        M_Downloadable_Template --|{ T_Downloadable_Data
        T_Run --|{ T_Downloadable_Data
        T_Downloadable_Data --|{ T_Download
        T_Run --|{ T_RunMeasure
    }

    T_TestDescription }|-- M_Quality_Dimension
    T_TestDescription -- M_TestRunner
    M_Quality_Measurement --|{ T_Operand
}

@enduml